include blob upload duration in the registration requests
snowflakedb/snowflake-ingest-java pull request #199
Opened 2022-07-20 14:34 UTC by sfc-gh-gdoci

This PR adds the file upload duration in ms and includes that information in the blob registration requests.

2022-07-20 17:28 UTC, sfc-gh-tjones commented on src/main/java/net/snowflake/ingest/streaming/internal/BlobMetadata.java
> +  @JsonProperty("upload_duration")
Let's change this to `upload_duration_ms`

2022-07-20 17:32 UTC, sfc-gh-japatel approved these changes
lgtm! can you run formatter. https://github.com/snowflakedb/snowflake-ingest-java#code-style before pushing? (Merge gate is failing)

2022-07-20 21:25 UTC, sfc-gh-tzhang requested changes
I assume this is for calculating the end to end ingestion latency? If yes, we're missing two big things here:
1. The time it takes to build a blob
2. The time a blob in the registration queue, waiting be to registered

So the start timestamp we should use for each blob is when we kick off the flush job, please take a look at `flush(boolean isForce)` in `FlushService.java`

2023-02-01 18:18 UTC, sfc-gh-gdoci commented
Duration information is added in other PRs.

2023-02-01 18:18 UTC, closed without merging