SNOW-684044 Fix nullability mismatch incidents
snowflakedb/snowflake-ingest-java pull request #278
Opened 2022-11-04 17:37 UTC by sfc-gh-lsembera

Nullability mismatch incidents were happening for columns with quoted names like "id". These names were being passed as "id", which XP did not understand, it expects just id.

2022-11-04 19:13 UTC, sfc-gh-tjones commented on src/main/java/net/snowflake/ingest/streaming/internal/ColumnMetadata.java
> +      return name;
Nit, you can reduce to:
```
return (name.length() >= 2 && name.charAt(0) == '"' && name.charAt(name.length() - 1) == '"') ?
   name.substring(1, name.length() - 1).replace("\"\"", "\"") : name;
```

2022-11-04 19:13 UTC, sfc-gh-tjones commented on src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java
> +    conn.createStatement().execute(String.format("alter table %s migrate;", tableName));
I don't think this is executable outside of Snowflake?

2022-11-04 19:14 UTC, sfc-gh-tjones commented on src/test/java/net/snowflake/ingest/streaming/internal/datatypes/ColumnNameIT.java
> +    migrateTable(name);
Can we trigger scanback without explicitly invoking `migrate`?

2022-11-04 20:39 UTC, sfc-gh-tzhang requested changes
I believe @sfc-gh-azagrebin is planning to do a similar fix for this issue, where we handle names with both double quotes and space, please chat with him to see if that's something that need help, thanks!

The JIRA is https://snowflakecomputing.atlassian.net/browse/SNOW-647377

2022-11-07 15:51 UTC, sfc-gh-lsembera commented
I discussed this issue with @sfc-gh-azagrebin and I am going to implement passing normalised column name from the server side instead of doing column name normalisation in the client. The new PR will supersede both this PR and https://github.com/snowflakedb/snowflake-ingest-java/pull/214. Closing.

2022-11-07 15:51 UTC, closed without merging