SNOW-801398 Tidy up shaded jar
snowflakedb/snowflake-ingest-java pull request #490
Opened 2023-05-03 12:01 UTC by sfc-gh-lsembera

This PR reorganizes our shaded JAR, so that the only top level packages are snowflake ones. All dependencies are shaded in to the package `net.snowflake.ingest.internal`.

The script `check_content.sh` has been adapted accordingly, it now only ignores a limited set of top-level files.

Additionally, this PR removes some unnecessary transitive dependencies, particularly those pulled in by hadoop-common.

Testing: dew tests (both Arrow and Parquet) have passed.

2023-05-04 00:34 UTC, sfc-gh-pbennes commented
Ah nice, didn't know someone else was looking at #356. I opened a draft: #492 but given the discussion in #356 I'm more inclined to suggest removal of shading altogether.

2023-05-04 13:36 UTC, leszekgruchala commented
@sfc-gh-pbennes That's fine, but the problem is that the shaded jars are not shaded correctly and are conflicting with same libraries in the class path https://github.com/snowflakedb/snowflake-ingest-java/issues/356

2023-05-04 16:29 UTC, sfc-gh-pbennes commented
> @sfc-gh-pbennes I agree that unshaded JAR is a better option and maybe it should be our primary artifact (i.e. instead of having `1.1.4` and `1.1.4-unshaded`, we could have `1.1.4` and `1.1.4-shaded`). But I would argue against the removal of shading because it can help in situations when the client requires a specific version of a dependency, but we are shipping with a different, incompatible version. Some potential suspects would be Hadoop or Jackson.

Yeah if we need to shade one or two things that's fine but we probably don't need to shade everything.

2023-05-04 18:08 UTC, sfc-gh-tjones approved these changes
I'm good with this but let's have Preston have the final say as I am not a Java wizard.

2023-05-04 18:23 UTC, sfc-gh-pbennes requested changes
I ran the version of check_content.sh from https://github.com/snowflakedb/snowflake-ingest-java/blob/f0137e6ef51a52a7ab90029fe8102043728a5a60/scripts/check_content.sh and noticed that unrelocated shaded snowflake-jdbc classes are present. snowflake-jdbc should either be relocated or excluded from shading:

```
[pbennes@SDP_DevVM-pbennes snowflake-ingest-java]$ scripts/check_content.sh | grep -v META-INF | head
[ERROR] Ingest SDK jar includes classes outside net.snowflake.ingest
Found classes in jar:
com/snowflake/client/jdbc/SnowflakeDriver.class
net/snowflake/client/core/AssertUtil.class
net/snowflake/client/core/BasicEvent$QueryState.class
```

2023-05-04 18:25 UTC, sfc-gh-japatel commented
> Ah nice, didn't know someone else was looking at #356. I opened a draft: #492 but given the discussion in #356 I'm more inclined to suggest removal of shading altogether.

Wouldnt removing shading altogether considered a behavior change? IIUC, this will force users of this jar to add more dependencies?

2023-05-04 18:40 UTC, sfc-gh-pbennes commented
> > Ah nice, didn't know someone else was looking at #356. I opened a draft: #492 but given the discussion in #356 I'm more inclined to suggest removal of shading altogether.
> 
> Wouldnt removing shading altogether considered a behavior change? IIUC, this will force users of this jar to add more dependencies?

For relocated dependencies yes because there would now be an interaction for dependencies with multiple uses in a project consuming the ingest sdk. If any our first-order dependencies (ex. hadoop) require us to pull in ancient versions of commonly used dependencies (ex. protobuf-java) continuing to shade those may make sense, if we can't just outright exclude them, to avoid irreconcilable differences for people consuming snowflake-ingest-sdk.

For unrelocated shaded dependencies _basically_ no because it's the same as if the dependency weren't shaded at all. The caveat here is that unrelocated shaded dependencies have the potential to be problematic due to the class conflict issue described in #492 where it's not going to be immediately obvious to someone consuming snowflake-ingest-sdk that they're going to get a version of those shaded unrelocated classes they may not expect depending on where snowflake-ingest-sdk appears in their pom.xml (assuming maven, IDK offhand how gradle etc. handles this problem).

Basically:
- Anything shaded MUST be relocated
- We should be highly selective about what gets shaded/relocated

2023-05-04 18:41 UTC, sfc-gh-pbennes commented on scripts/check_content.sh
> +    grep -v -E "^(net|com)/snowflake" | \
This line should be adjusted to only cover the classes in this project. Currently it misses the shaded unrelocated snowflake-jdbc classes.

2023-05-04 19:32 UTC, sfc-gh-pbennes approved these changes
This LGTM with snowflake-jdbc excluded and the update to check_content.sh

2023-05-04 19:45 UTC, sfc-gh-tzhang commented
> @sfc-gh-pbennes I agree that unshaded JAR is a better option and maybe it should be our primary artifact (i.e. instead of having `1.1.4` and `1.1.4-unshaded`, we could have `1.1.4` and `1.1.4-shaded`). But I would argue against the removal of shading because it can help in situations when the client requires a specific version of a dependency, but we are shipping with a different, incompatible version. Some potential suspects would be Hadoop or Jackson.

I don't think now it's a good time to update the default behavior, this would be a big behavior change that needs to be communicated with customers carefully and we haven't heard many complains so far. I suggest we keep releasing `1.1.4` and `1.1.4-unshaded,` customers that want the unshaded version could use that and then we could see the usage from internal telemetry to conclude on the direction we want to go.

2023-05-04 19:50 UTC, sfc-gh-tzhang approved these changes
LGTM, thanks @sfc-gh-lsembera !

2023-05-04 19:50 UTC, sfc-gh-tzhang commented on pom.xml
> +
nit: remove extra space?

2023-05-04 19:56 UTC, sfc-gh-pbennes commented
> > @sfc-gh-pbennes I agree that unshaded JAR is a better option and maybe it should be our primary artifact (i.e. instead of having `1.1.4` and `1.1.4-unshaded`, we could have `1.1.4` and `1.1.4-shaded`). But I would argue against the removal of shading because it can help in situations when the client requires a specific version of a dependency, but we are shipping with a different, incompatible version. Some potential suspects would be Hadoop or Jackson.
> 
> I don't think now it's a good time to update the default behavior, this would be a big behavior change that needs to be communicated with customers carefully and we haven't heard many complains so far. I suggest we keep releasing `1.1.4` and `1.1.4-unshaded,` customers that want the unshaded version could use that and then we could see the usage from internal telemetry to conclude on the direction we want to go.

Agreed. My comments are more on the direction and long term goals and less on the immediate PR which is a step in the right direction.

2023-05-05 16:00 UTC, sfc-gh-lsembera commented on pom.xml
> +
Fixed

2023-05-05 17:21 UTC, merged