Release 2.3.0-unshaded
snowflakedb/snowflake-ingest-java pull request #860
Opened 2024-10-11 17:08 UTC by sfc-gh-xhuang

2024-10-14 16:27 UTC, sfc-gh-xhuang commented
@sfc-gh-azagrebin yes you can use this branch and commit for the unshaded release.
No need to merge this

2024-10-14 18:40 UTC, sfc-gh-asen approved these changes

2024-10-15 00:16 UTC, sfc-gh-tzhang approved these changes

2024-10-15 00:18 UTC, sfc-gh-tzhang requested changes
Want to make sure this is on top of https://github.com/snowflakedb/snowflake-ingest-java/commit/e4b335f313c6fbf851567ffdc9ba13928e574635 instead of master?

2024-10-15 16:15 UTC, sfc-gh-xhuang commented
Yes the branch was created right after from the 2.3.0 release

2024-10-29 22:45 UTC, closed without merging